server:
  port: 8111

spring:
  codec:
    max-in-memory-size: 10MB
  datasource:
    # values for url, username and password will be provided by vault on non-local environments
    url: jdbc:postgresql://localhost:5440/dbs_kapitanov_info?currentSchema=scm_info_app
    username: info_bot_user
    password: password
    driver-class-name: org.postgresql.Driver

telegram:
    key: "1480130133:AAEaRPW2XhZXgeVYJuGqpNw986w-VnGuQxA"
    user-name: "@kapitanov_transport_bot"
    url: "https://api.telegram.org/bot"

geocode:
  url: "https://nominatim.openstreetmap.org/search"

weather:
  url: "https://api.openweathermap.org/data/2.5/weather"
  key: 7491ac20be0abaf40895e0cf831e05d0

air-pollution:
  url: "http://api.openweathermap.org/data/2.5/air_pollution"
  key: 7491ac20be0abaf40895e0cf831e05d0