CREATE SCHEMA IF NOT EXISTS scm_info_app;

CREATE TABLE scm_info_app.reminder (
    ID SERIAL PRIMARY KEY,
    CHAT_ID BIGINT,
    REMINDER_AT DATE NOT NULL,
    REMINDER_TEXT VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);